### ISSUE TITLE
Unable to converto to mp3

### ISSUE THREAD

**Issue by AndreaSalmaso** [harshanas/ZamzarConverter#3]
Hi, I'm trying to convert a .docx file to mp3, but I get this error
```
Traceback (most recent call last):
  File "C:\Users\gedeo\OneDrive\Documenti\Python\Zamzar Converter\convert.py", line 63, in <module>
    jobId = initJobData['id']
KeyError: 'id'
```
I tried converting it to .pdf and It worked smoothly, so what's the problem here?
Thanks

**Comment by goodmuyis** [comment]
> Hi, I'm trying to convert a .docx file to mp3, but I get this error
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\gedeo\OneDrive\Documenti\Python\Zamzar Converter\convert.py", line 63, in <module>
>     jobId = initJobData['id']
> KeyError: 'id'
> ```
> 
> I tried converting it to .pdf and It worked smoothly, so what's the problem here? Thanks

The API cannot convert documents to mp3.  Check their website https://developers.zamzar.com/formats
